# These are config values that users can set from the GUI or the commandline
options:
  bitbucket-client-id:
    type: string
    default:
    description: A Bitbucket OAuth Consumer Key
  bitbucket-client-secret:
    type: string
    default:
    description: A Bitbucket OAuth Consumer Key's Secret
  github-client-id:
    type: string
    default:
    description: A GitHub OAuth Client ID
  github-client-secret:
    type: string
    default:
    description: A GitHub OAuth Client Secret
  github-server:
    type: string
    default:
    description: A GitHub Enterprise Server Address (Not required if using public GitHub)
  gitlab-client-id:
    type: string
    default:
    description: A GitLab OAuth Client ID
  gitlab-client-secret:
    type: string
    default:
    description: A GitLab OAuth Client Secret
  gitlab-server:
    type: string
    default:
    description: A GitLab Server Address
  gitlab-always-auth:
    type: boolean
    default: false
    description: >
      DRONE_GIT_ALWAYS_AUTH: 
      Optional boolean value configures Drone to authenticate when cloning public repositories. 
      This should only be enabled when using self-hosted GitLab with private mode enable.
  gitea-client-id:
    type: string
    default:
    description: A Gitea OAuth Client ID
  gitea-client-secret:
    type: string
    default:
    description: A Gitea OAuth Client Secret
  gitea-server:
    type: string
    default:
    description: A Gitea Server Address
  admin:
    type: string
    default:
    description: Drone Admin user
  server-host:
    type: string
    default:
    description: Host or domain name Drone will be served under
  server-proto:
    type: string
    default: https
    description: Protocol under which your host or domain will be served publicly. (Either 'http' or 'https')
  server-secret:
    type: string
    default:
    description: >
      DRONE_RPC_SECRET: 
      Provides the shared secret used by the Drone server to authenticate http requests. Drone Runners need
      to provide this secret to connect to the server. If not provided here, a random secret will be generated
      for communication with related charms. However, if remote Runners need to connect, i.e. external to Juju,
      then providing a secret here is the only way to ensure you can provide the correct secret to connect, as 
      the secret is not exposed otherwise and is kept hidden within the Juju charming internals.
  server-volume:
    type: string
    default:
    description: Volume name or absolute path for Drone Server data persistence
  tls-autocert:
    type: boolean
    default: false
    description: If true, generates a free SSL Cert via LetsEncrypt.
