# These are config values that users can set from the GUI or the commandline
options:
  rpc-secret:
    type: string
    default: 
    description: Shared secret for connecting to Drone Server
  rpc-host:
    type: string
    default: 
    description: Host or domain name of the Drone Server
  rpc-proto:
    type: string
    default: http
    description: Protocol for Drone Server communication
